# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 19:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20160622_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='publish',
            field=models.DateField(default=datetime.datetime(2016, 6, 23, 19, 8, 49, 980200, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
